<?php

$config = array(
    'version'               => 'vb3x_4.9.4',
    'api_level'             => 3,
    'is_open'               => 1,
    'guest_okay'            => 1,
    'allow_trending'        => 1,

    'allowed_usergroup'     => '',
    'hide_forum_id'         => '',
    'byo_new_group'         => '',
    'disable_search'        => 0,
    'disable_latest'        => 0,

    'allow_moderate'        => 1,
    'disable_bbcode'        => 0,

    'mark_forum'            => 1,
    'mark_read'             => 1,
    'ban_delete_type'       => 'soft_delete',
    'forum_signature'       => 1,
    'emoji'                 => 1,
    'emoji_support'         => 1,
    'prefix_edit'           => 1,
    'avatar'                => 1,
    'searchid'              => 1,

    'subscribe_load'        => 1,
    'anonymous'             => 1,
    'push'                  => 1,
    'advanced_search'       => 1,
    'user_id'               => 1,
    'alert'                 => 1,
    'advanced_online_users' => 1,
    'push_type'             => 'quote,tag,newtopic,pm,sub',
    'announcement'          => 1,
    'pm_load'               => 1,
    'mark_pm_unread'        => 1,
    'inappsignin'           => 1,
    'ignore_user'           => 1,
    'search_user'           => 1,
    'user_recommended'      => 1,
    'm_approve'             => 1,
    'm_delete'              => 1,
    'advanced_delete'       => 1,
    'sign_in'               => 1,
    'inappreg'              => 1,
    'sso_login'             => 1,
    'sso_signin'            => 1,
    'sso_register'          => 1,
    'native_register'       => 1,
    'advanced_edit'         => 1,
    'ban_expires'           => 1,
    'get_contact'           => 1,
    'advanced_reg'          => 1,
    'login_type'            => 'username',
    'sso_activate'          => 1,
);
